source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'Starglobe' do
use_frameworks!
pod 'Realm'
pod 'MZFormSheetPresentationController'
pod 'UIAlertController+Blocks'
pod 'Branch'
pod 'ZendeskSDK'
pod 'STPopup'
pod 'MBProgressHUD'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'UAAppReviewManager'
end

target 'Starglobe Free' do
use_frameworks!
pod 'Realm'
pod 'MZFormSheetPresentationController'
pod 'UIAlertController+Blocks'
pod 'Branch'
pod 'ZendeskSDK'
pod 'STPopup'
pod 'MBProgressHUD'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'UAAppReviewManager'
pod 'SCPStoreKitManager'
pod 'GLInAppPurchase'
pod 'KiipSDK'
pod 'FyberSDK', '~> 8.11.0'
pod 'FyberMediationAdColony', '~> 3.1.1.1'
pod 'FyberMediationAdMob', '~> 7.16.0.1'
pod 'FyberMediationAppLovin', '~> 3.5.2.2'
pod 'FyberMediationFacebookAudienceNetwork', '~> 4.21.0.1'
pod 'FyberMediationInMobi', '~> 6.1.1.1'
pod 'FyberMediationNativeX', '~> 5.5.9.1'
pod 'FyberMediationTapjoy', '~> 11.9.1.1'
pod 'FyberMediationUnityAds', '~> 2.0.7.2'
pod 'FyberMediationVungle', '~> 4.0.9.2'
pod 'FyberMediationLoopMe', '~> 6.0.1.1'
pod 'FyberMediationInneractive', '~> 6.4.1.2'
pod 'FyberMediationHyprMX', '~> 4.2.0.78.3'
end